[phases.setup]
nixPkgs = ['python311', 'poetry', 'gcc']

[phases.install]
cmds = ['poetry config virtualenvs.create false', 'poetry install --no-dev --no-interaction']

[start]
cmd = 'poetry run uvicorn main:app --host 0.0.0.0 --port $PORT'